services:
  - type: web
    name: docurag-app
    env: python
    buildCommand: |
      pip install --upgrade pip
      # Install faiss-cpu explicitly
      pip install --no-cache-dir faiss-cpu==1.7.4
      # Install rest of dependencies
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 10000 --server.address 0.0.0.0


