services:
  - type: web
    name: docurag
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
